// <auto-generated />
using System;
using LogicLink.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogicLink.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogicLink.Api.Models.Entities.Circuit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GridSize")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("ShowGateLabels")
                        .HasColumnType("boolean");

                    b.Property<bool>("SnapToGrid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Circuits");
                });

            modelBuilder.Entity("LogicLink.Api.Models.Entities.Gate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("InputValue")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<double>("Rotation")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("LogicLink.Api.Models.Entities.Wire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromGateId")
                        .HasColumnType("uuid");

                    b.Property<int>("FromPinIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToGateId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToPinIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId", "FromGateId");

                    b.HasIndex("CircuitId", "ToGateId");

                    b.ToTable("Wires");
                });

            modelBuilder.Entity("LogicLink.Api.Models.Entities.Gate", b =>
                {
                    b.HasOne("LogicLink.Api.Models.Entities.Circuit", "Circuit")
                        .WithMany("Gates")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("LogicLink.Api.Models.Entities.Wire", b =>
                {
                    b.HasOne("LogicLink.Api.Models.Entities.Circuit", "Circuit")
                        .WithMany("Wires")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("LogicLink.Api.Models.Entities.Circuit", b =>
                {
                    b.Navigation("Gates");

                    b.Navigation("Wires");
                });
#pragma warning restore 612, 618
        }
    }
}
