using LogicLink.Api.Data;
using LogicLink.Api.Models.Entities;
using LogicLink.Api.Models.Enums;
using LogicLink.Api.Extensions;
using LogicLink.Api.Services.Interfaces;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using SkiaSharp;

namespace LogicLink.Api.Services;

public class PdfExportService : IPdfExportService
{
    private const float GateWidth = 90f;
    private const float GateHeight = 50f;
    private const float Margin = 40f;

    private readonly AppDbContext _db;

    public PdfExportService(AppDbContext db)
    {
        _db = db;
    }

    public async Task<byte[]?> ExportCircuitAsync(Guid circuitId)
    {
        var circuit = await _db.Circuits
            .Include(c => c.Gates)
            .Include(c => c.Wires)
            .FirstOrDefaultAsync(c => c.Id == circuitId && !c.IsDeleted);

        if (circuit is null) return null;

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4.Landscape());
                page.Margin(Margin);

                page.Header().Column(col =>
                {
                    col.Item().Text(circuit.Name).FontSize(20).Bold();
                    col.Item().Text($"Owner: {circuit.OwnerName}  ·  Exported: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC")
                        .FontSize(9).FontColor(Colors.Grey.Darken1);
                });

                page.Content().PaddingTop(16).SkiaSharpSvgCanvas((canvas, size) =>
                    DrawCircuitDiagram(canvas, size, circuit.Gates.ToList(), circuit.Wires.ToList()));

                page.Footer().AlignCenter().Text("Generated by LogicLink").FontSize(8).FontColor(Colors.Grey.Medium);
            });
        });

        return document.GeneratePdf();
    }

    private static void DrawCircuitDiagram(SKCanvas canvas, QuestPDF.Infrastructure.Size size, List<Gate> gates, List<Wire> wires)
    {
        if (gates.Count == 0)
        {
            using var emptyFont = new SKFont { Size = 14 };
            using var emptyPaint = new SKPaint { Color = SKColors.Gray, IsAntialias = true };
            canvas.DrawText("This circuit has no gates yet.", 0, 20, SKTextAlign.Left, emptyFont, emptyPaint);
            return;
        }

        var scale = ComputeFitScale(gates, size);
        var offsetX = gates.Min(g => (float)g.X);
        var offsetY = gates.Min(g => (float)g.Y);

        Point Project(double x, double y) => new(
            (float)((x - offsetX) * scale),
            (float)((y - offsetY) * scale));

        DrawWires(canvas, gates, wires, Project);
        DrawGates(canvas, gates, scale, Project);
    }

    private static void DrawWires(SKCanvas canvas, List<Gate> gates, List<Wire> wires, Func<double, double, Point> project)
    {
        using var wirePaint = new SKPaint
        {
            Color = new SKColor(0xC1, 0x79, 0x3F), 
            StrokeWidth = 1.6f,
            IsStroke = true,
            IsAntialias = true
        };

        var gatesById = gates.ToDictionary(g => g.Id);

        foreach (var wire in wires)
        {
            if (!gatesById.TryGetValue(wire.FromGateId, out var from) || !gatesById.TryGetValue(wire.ToGateId, out var to))
                continue; 

            var start = project(from.X + GateWidth, from.Y + GateHeight / 2);
            var end = project(to.X, to.Y + GateHeight / 2);
            canvas.DrawLine(start.X, start.Y, end.X, end.Y, wirePaint);
        }
    }

    private static void DrawGates(SKCanvas canvas, List<Gate> gates, float scale, Func<double, double, Point> project)
    {
        using var boxPaint = new SKPaint { Color = SKColors.White, IsStroke = false, IsAntialias = true };
        using var borderPaint = new SKPaint { Color = new SKColor(0x2A, 0x3F, 0x35), StrokeWidth = 1.2f, IsStroke = true, IsAntialias = true };

        
        using var typeFont = new SKFont { Size = 12 * scale };
        using var typePaint = new SKPaint { Color = new SKColor(0x4F, 0xB8, 0xA6), IsAntialias = true };

        using var labelFont = new SKFont { Size = 10 * scale };
        using var labelPaint = new SKPaint { Color = SKColors.Black, IsAntialias = true };

        foreach (var gate in gates)
        {
            var topLeft = project(gate.X, gate.Y);
            var width = GateWidth * scale;
            var height = GateHeight * scale;
            var rect = new SKRect(topLeft.X, topLeft.Y, topLeft.X + width, topLeft.Y + height);

            canvas.DrawRoundRect(rect, 4 * scale, 4 * scale, boxPaint);
            canvas.DrawRoundRect(rect, 4 * scale, 4 * scale, borderPaint);

            canvas.DrawText(GateTypeLabel(gate.Type), rect.MidX, rect.Top + height * 0.42f, SKTextAlign.Center, typeFont, typePaint);
            if (!string.IsNullOrWhiteSpace(gate.Label))
                canvas.DrawText(gate.Label, rect.MidX, rect.Top + height * 0.78f, SKTextAlign.Center, labelFont, labelPaint);
        }
    }

    private static string GateTypeLabel(GateType type) => type switch
    {
        GateType.Input => "IN",
        GateType.Output => "OUT",
        _ => type.ToString().ToUpperInvariant()
    };

    private static float ComputeFitScale(List<Gate> gates, QuestPDF.Infrastructure.Size availableSize)
    {
        var spanX = (float)(gates.Max(g => g.X) - gates.Min(g => g.X)) + GateWidth;
        var spanY = (float)(gates.Max(g => g.Y) - gates.Min(g => g.Y)) + GateHeight;

        if (spanX <= 0 || spanY <= 0) return 1f;

        var scaleX = availableSize.Width / spanX;
        var scaleY = availableSize.Height / spanY;

        return Math.Min(Math.Min(scaleX, scaleY), 1.5f);
    }

    private readonly record struct Point(float X, float Y);
}